version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: modern_pwa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modern_pwa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:7
    container_name: modern_pwa_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: modern_pwa_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    container_name: modern_pwa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  mongo_data:
  redis_data:
