services:
  - type: web
    name: sinsier-client
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
    plan: free
    autoDeploy: true
